// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOM22D-TQLV4PuKKTFJ6BQPsb9mOOfgFU',
    appId: '1:830436214415:web:166cfe81e465a24ce852fa',
    messagingSenderId: '830436214415',
    projectId: 'islamic-chat-app-38906',
    authDomain: 'islamic-chat-app-38906.firebaseapp.com',
    storageBucket: 'islamic-chat-app-38906.firebasestorage.app',
    measurementId: 'G-H3GDBT829G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8mGnOnJt7FxvvhhsM7z0_MzNfCLL_6Q',
    appId: '1:830436214415:android:07f44abd68bc3ec2e852fa',
    messagingSenderId: '830436214415',
    projectId: 'islamic-chat-app-38906',
    storageBucket: 'islamic-chat-app-38906.firebasestorage.app',
  );

}